version: "3.9"

services:
  app:
    build:
      context: ./docker/php
    container_name: skybroker-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/conf.d/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  web:
    image: nginx:1.27-alpine
    container_name: skybroker-web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      app:
        condition: service_started

  mysql:
    image: mysql:8.0
    container_name: skybroker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skybroker
      MYSQL_USER: skybroker
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: skybroker-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: skybroker-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: skybroker
      PMA_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy

  mailpit:
    image: axllent/mailpit:latest
    container_name: skybroker-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql_data:
